### ISSUE TITLE
 Invalid syntax error when running offical python package

### ISSUE THREAD

**Issue by ghost** [ERROR-404-NULL-NOT-FOUND/Retaped-TUI#1]
```
$ retaped-tui
Traceback (most recent call last):
  File "/home/owner/anaconda3/bin/retaped-tui", line 8, in <module>
    sys.exit(run())
  File "/home/owner/anaconda3/lib/python3.9/site-packages/retaped_tui/__init__.py", line 2, in run
    from . import main
  File "/home/owner/anaconda3/lib/python3.9/site-packages/retaped_tui/main.py", line 89
    match(message['type']):
                           ^
SyntaxError: invalid syntax
```

**Comment by ERROR-404-NULL-NOT-FOUND** [comment]
What the fuck?
Lemme look into it.

**Comment by ERROR-404-NULL-NOT-FOUND** [comment]
Oh, it's because of the python version.
It's supposed to require >= 3.10.

**Comment by ghost** [comment]
Yep it was me using python <= 3.10 (more specifically python 3.9.13). Fixed it by just using pipx to install with python >= 3.10 (more specifically 3.10.12). Thanks for the help!
